services:
  reactive-resume:
    image: amruthpillai/reactive-resume:latest
    container_name: reactive-resume
    environment:
      PUBLIC_URL: http://192.168.22.204:3000

      DATABASE_URL: postgresql://resume:resume@postgres:5432/reactive_resume
      REDIS_URL: redis://redis:6379

      # STORAGE (MINIO)
      STORAGE_URL: http://minio:9000
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      STORAGE_BUCKET: resumes
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: minioadmin

      # PDF
      CHROME_URL: http://chrome:3000
      CHROME_TOKEN: chrometoken

      ACCESS_TOKEN_SECRET: supersecretaccess
      REFRESH_TOKEN_SECRET: supersecretrefresh

      HOST: 0.0.0.0
      PORT: 3000

    depends_on:
      - postgres
      - redis
      - minio
      - chrome
    ports:
      - "3000:3000"
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: reactive_resume
      POSTGRES_USER: resume
      POSTGRES_PASSWORD: resume
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  chrome:
    image: browserless/chrome:latest
    container_name: chrome
    environment:
      TOKEN: chrometoken
    expose:
      - "3000"
    ports:
      - "9222:3000"

volumes:
  postgres_data:
  minio_data:
